<a href="https://colab.research.google.com/github/amatyaagrata/ConceptandTechnologyofAI/blob/main/Workshop1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np

# 1. Initialize an empty array with size 2X2
empty_array = np.empty((2, 2))
print("Empty Array (2x2):", empty_array)

# 2. Initialize an all one array with size 4X2
ones_array = np.ones((4, 2))
print("All Ones Array (4x2):", ones_array)

# 3. Return a new array of given shape and type, filled with fill value
full_array = np.full((3, 3), 7)
print("Full Array (3x3 filled with 7):", full_array)

# 4. Return a new array of zeros with same shape and type as a given array
given_array = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like_array = np.zeros_like(given_array)
print("Zeros Like Array:", zeros_like_array)

# 5. Return a new array of ones with same shape and type as a given array
ones_like_array = np.ones_like(given_array)
print("Ones Like Array:", ones_like_array)

# 6. Convert an existing list to numpy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("Converted Numpy Array:", numpy_array)


Empty Array (2x2): [[3.83630901e-315 0.00000000e+000]
 [5.31410685e-317 6.77990793e-310]]
All Ones Array (4x2): [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Full Array (3x3 filled with 7): [[7 7 7]
 [7 7 7]
 [7 7 7]]
Zeros Like Array: [[0 0 0]
 [0 0 0]]
Ones Like Array: [[1 1 1]
 [1 1 1]]
Converted Numpy Array: [1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
import numpy as np

# 1. Create an array with values ranging from 10 to 49
arr1 = np.arange(10, 50)
print("Array from 10 to 49:", arr1)

# 2. Create a 3X3 matrix with values ranging from 0 to 8
arr2 = np.arange(9).reshape(3, 3)
print("3x3 Matrix (0 to 8):", arr2)

# 3. Create a 3X3 identity matrix
identity_matrix = np.eye(3)
print("3x3 Identity Matrix:", identity_matrix)

# 4. Create a random array of size 30 and find the mean
random_array = np.random.random(30)
mean_value = random_array.mean()
print("Random Array (size 30):", random_array)
print("Mean of Random Array:", mean_value)

# 5. Create a 10X10 array with random values and find min & max
random_matrix = np.random.random((10, 10))
min_val, max_val = random_matrix.min(), random_matrix.max()
print("10x10 Random Matrix:", random_matrix)
print("Minimum Value:", min_val)
print("Maximum Value:", max_val)

# 6. Create a zero array of size 10 and replace 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1   # Index 4 is the 5th element
print("Zero Array with 5th element replaced: ", zero_array)

# 7. Reverse an array arr = [1,2,0,0,4,0]
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("Reversed Array:", reversed_arr)

# 8. Create a 2d array with 1 on border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("2D Array with Border 1 and Inside 0:", border_array)

# 9. Create an 8X8 matrix and fill it with a checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("8x8 Checkerboard Pattern:", checkerboard)


Array from 10 to 49: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
3x3 Matrix (0 to 8): [[0 1 2]
 [3 4 5]
 [6 7 8]]
3x3 Identity Matrix: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random Array (size 30): [0.96644294 0.40954714 0.20048592 0.21444649 0.9278053  0.2988627
 0.31632504 0.78572988 0.66964735 0.00657628 0.49312339 0.80777668
 0.79024057 0.65601492 0.24454888 0.84988607 0.05037542 0.32559166
 0.8039843  0.026953   0.83687027 0.69991393 0.48588396 0.35336036
 0.43528771 0.75207155 0.0276925  0.76693196 0.82875007 0.04498349]
Mean of Random Array: 0.50253699115518
10x10 Random Matrix: [[0.41926233 0.6861508  0.99250239 0.91061448 0.61814423 0.22810722
  0.36614406 0.00740466 0.09564953 0.79290345]
 [0.97629387 0.04008984 0.20579938 0.13707134 0.99188107 0.04161636
  0.44229065 0.8809243  0.85412077 0.99737769]
 [0.96110599 0.21516502 0.43110424 0.91783595 0.33884065 0.16584493
  0.88691092 0.56167695 0.038342

Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])


In [ ]:
# 1. Add the two arrays
add_xy = x + y
print("Addition of x and y:\n", add_xy)

# 2. Subtract the two arrays
sub_xy = x - y
print("Subtraction of x and y:", sub_xy)

# 3. Multiply the array with any integer (say 3)
mul_x = x * 3
print("\nMultiplication of x with 3:\n", mul_x)

# 4. Find the square of each element of the array
square_x = np.square(x)
print("Square of each element in x:", square_x)

# 5. Dot products
dot_vw = np.dot(v, w)       # vector dot product
dot_xv = np.dot(x, v)       # matrix-vector product
dot_xy = np.dot(x, y)       # matrix-matrix product
print("Dot product v·w:", dot_vw)
print("Dot product x·v:", dot_xv)
print("Dot product x·y:", dot_xy)

# 6. Concatenate x and y along row
concat_xy_row = np.concatenate((x, y), axis=0)
print("Concatenate x and y along row:", concat_xy_row)

# Concatenate v and w along column
concat_vw_col = np.column_stack((v, w))
print("Concatenate v and w along column:", concat_vw_col)

# 7. Concatenate x and v
try:
    concat_xv = np.concatenate((x, v), axis=0)
    print("Concatenate x and v:", concat_xv)
except ValueError as e:
    print("Error when concatenating x and v:", e)


Addition of x and y:
 [[ 6  8]
 [10 13]]
Subtraction of x and y: [[-4 -4]
 [-4 -3]]

Multiplication of x with 3:
 [[ 3  6]
 [ 9 15]]
Square of each element in x: [[ 1  4]
 [ 9 25]]
Dot product v·w: 219
Dot product x·v: [29 77]
Dot product x·y: [[19 22]
 [50 58]]
Concatenate x and y along row: [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along column: [[ 9 11]
 [10 12]]
Error when concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [3]:
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])


1. Prove
𝐴
⋅
𝐴
−
1
=
𝐼

In [4]:
A_inv = np.linalg.inv(A)       # Inverse of A
identity = np.dot(A, A_inv)    # Multiply A with its inverse
print("A * A^-1:\n", identity)


A * A^-1:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


2. Prove
𝐴
𝐵
≠
𝐵
𝐴

In [5]:
AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB:\n", AB)
print("BA:\n", BA)


AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]


3. Prove
(
𝐴
𝐵
)
𝑇
=
𝐵
𝑇
𝐴
𝑇

In [6]:
lhs = np.transpose(np.dot(A, B))   # (AB)^T
rhs = np.dot(np.transpose(B), np.transpose(A))  # B^T A^T
print("(AB)^T:\n", lhs)
print("B^T A^T:\n", rhs)


(AB)^T:
 [[23 51]
 [13 29]]
B^T A^T:
 [[23 51]
 [13 29]]


{
2
𝑥
−
3
𝑦
+
𝑧
=
−
1
𝑥
−
𝑦
+
2
𝑧
=
−
3
3
𝑥
+
𝑦
−
𝑧
=
9

In [10]:
# Coefficient matrix A
coeff = np.array([[2, -3, 1],
                  [1, -1, 2],
                  [3,  1, -1]])

# Constants vector B
const = np.array([-1, -3, 9])


Step 2: Solve using Inverse Method

In [9]:
# Solve using inverse
solution = np.dot(np.linalg.inv(coeff), const)
print("Solution [x, y, z]:", solution)


Solution [x, y, z]: [ 2.  1. -2.]


In [11]:
import numpy as np
import time

# 1. Element-wise Addition
# Python Lists
list1 = list(range(1000000))
list2 = list(range(1000000))
start = time.time()
list_add = [a + b for a, b in zip(list1, list2)]
end = time.time()
print("Python List Addition Time:", end - start)

# NumPy Arrays
arr1 = np.arange(1000000)
arr2 = np.arange(1000000)
start = time.time()
arr_add = arr1 + arr2
end = time.time()
print("NumPy Array Addition Time:", end - start)

# 2. Element-wise Multiplication
# Python Lists
start = time.time()
list_mul = [a * b for a, b in zip(list1, list2)]
end = time.time()
print("Python List Multiplication Time:", end - start)

# NumPy Arrays
start = time.time()
arr_mul = arr1 * arr2
end = time.time()
print("NumPy Array Multiplication Time:", end - start)

# 3. Dot Product
# Python Lists
start = time.time()
dot_list = sum(a * b for a, b in zip(list1, list2))
end = time.time()
print("Python List Dot Product Time:", end - start)

# NumPy Arrays
start = time.time()
dot_arr = np.dot(arr1, arr2)
end = time.time()
print("NumPy Array Dot Product Time:", end - start)

# 4. Matrix Multiplication

# Python Lists (nested loops)
matrix1 = [[i for i in range(1000)] for j in range(1000)]
matrix2 = [[i for i in range(1000)] for j in range(1000)]

start = time.time()
result_matrix = [[sum(a*b for a, b in zip(row, col))
                  for col in zip(*matrix2)]
                  for row in matrix1]
end = time.time()
print("Python List Matrix Multiplication Time:", end - start)

# NumPy Arrays
mat1 = np.arange(1000000).reshape(1000, 1000)
mat2 = np.arange(1000000).reshape(1000, 1000)

start = time.time()
result_np = np.dot(mat1, mat2)
end = time.time()
print("NumPy Matrix Multiplication Time:", end - start)


Python List Addition Time: 0.06919670104980469
NumPy Array Addition Time: 0.0037622451782226562
Python List Multiplication Time: 0.08330583572387695
NumPy Array Multiplication Time: 0.006402015686035156
Python List Dot Product Time: 0.09912586212158203
NumPy Array Dot Product Time: 0.0020360946655273438
Python List Matrix Multiplication Time: 174.1676754951477
NumPy Matrix Multiplication Time: 3.0590415000915527
